export enum FieldNameEnum {
    //VAR COMMMONS
    FIRSTNAME = "FIRSTNAME",
    SURVEYDATE = "SURVEYDATE",

    //TIME
    START_TIME = "START_TIME",
    END_TIME = "END_TIME",

    //SUGGESTER
    INPUT_SUGGESTER = "INPUT_SUGGESTER",

    //PLACE
    PLACE = "PLACE",

    //WITH SOMEONE
    WITHSOMEONE = "WITHSOMEONE",
    COUPLE = "COUPLE",
    PARENTS = "PARENTS",
    CHILD = "CHILD",
    OTHERKNOWN = "OTHERKNOWN",
    OTHER = "OTHER",
    WITHSCREEN = "WITHSCREEN",

    // VARIABLES CLOTURE

    GREATESTACTIVITYDAY = "GREATESTACTIVITYDAY",
    WORSTACTIVITYDAY = "WORSTACTIVITYDAY",
    KINDOFDAY = "KINDOFDAY",
    EXCEPTIONALDAY = "EXCEPTIONALDAY",
    TRAVELTIME = "TRAVELTIME",
    PHONETIME = "PHONETIME",

    ISCLOSED = "ISCLOSED", //SURVEY CLOSED
    ISENVOYED = "ISENVOYED", //SURVEY ENVOYED
    ISROUTE = "ISROUTE", // IS ROUTE
    ISCOMPLETED = "ISCOMPLETED", // ALL VARIABLES SET FOR SURVEY
    ISVALIDATED = "ISVALIDATED", //SURVEY VALIDATED
    ISLOCKED = "ISLOCKED", //SURVEY LOCKED

    //ACTIVITY

    //MAIN ACTIVITY
    ACTIVITY_SELECTER_HISTORY = "ACTIVITY_SELECTER_HISTORY",
    MAINACTIVITY_ID = "MAINACTIVITY_ID",
    MAINACTIVITY_SUGGESTERID = "MAINACTIVITY_SUGGESTERID",
    MAINACTIVITY_ISFULLYCOMPLETED = "MAINACTIVITY_ISFULLYCOMPLETED",
    MAINACTIVITY_LABEL = "MAINACTIVITY_LABEL",
    GOAL = "GOAL",

    //SECONDARY ACTIVITY
    WITHSECONDARYACTIVITY = "WITHSECONDARYACTIVITY",
    SECONDARYACTIVITY = "SECONDARYACTIVITY",
    SECONDARYACTIVITY_LABEL = "SECONDARYACTIVITY_LABEL",
    SECONDARYACTIVITY_SUGGESTERID = "SECONDARYACTIVITY_SUGGESTERID",

    //SCORE
    QUALITY_SCORE = "QUALITY_SCORE", //QUALITY SCORE
    QUALITY_SCORE_SUBSTRACT_POINTS = "QUALITY_SCORE_SUBSTRACT_POINTS", //POINT TO SUBSTRACT FOR CALCULATE SCORE

    //ROUTE
    ROUTE = "ROUTE",
    FOOT = "FOOT",
    BICYCLE = "BICYCLE",
    TWOWHEELSMOTORIZED = "TWOWHEELSMOTORIZED",
    PRIVATECAR = "PRIVATECAR",
    OTHERPRIVATE = "OTHERPRIVATE",
    PUBLIC = "PUBLIC",

    //WEEKLY PLANNER
    WEEKLYPLANNER = "WEEKLYPLANNER",
    DATES = "DATES",
    DATES_STARTED = "DATES_STARTED",
    WEEKTYPE = "WEEKTYPE",
}

export enum FieldNameEnumActivity {
    //VAR COMMMONS
    FIRSTNAME = "FIRSTNAME",
    SURVEYDATE = "SURVEYDATE",

    //TIME
    START_TIME = "START_TIME",
    END_TIME = "END_TIME",

    //SUGGESTER
    INPUT_SUGGESTER = "INPUT_SUGGESTER",

    //PLACE
    PLACE = "PLACE",

    //WITH SOMEONE
    WITHSOMEONE = "WITHSOMEONE",
    COUPLE = "COUPLE",
    PARENTS = "PARENTS",
    CHILD = "CHILD",
    OTHERKNOWN = "OTHERKNOWN",
    OTHER = "OTHER",
    WITHSCREEN = "WITHSCREEN",

    // VARIABLES CLOTURE

    GREATESTACTIVITYDAY = "GREATESTACTIVITYDAY",
    WORSTACTIVITYDAY = "WORSTACTIVITYDAY",
    KINDOFDAY = "KINDOFDAY",
    EXCEPTIONALDAY = "EXCEPTIONALDAY",
    TRAVELTIME = "TRAVELTIME",
    PHONETIME = "PHONETIME",

    ISCLOSED = "ISCLOSED", //SURVEY CLOSED
    ISENVOYED = "ISENVOYED", //SURVEY ENVOYED
    ISROUTE = "ISROUTE", // IS ROUTE
    ISCOMPLETED = "ISCOMPLETED", // ALL VARIABLES SET FOR SURVEY
    ISVALIDATED = "ISVALIDATED", //SURVEY VALIDATED
    ISLOCKED = "ISLOCKED", //SURVEY LOCKED

    //ACTIVITY

    //MAIN ACTIVITY
    ACTIVITY_SELECTER_HISTORY = "ACTIVITY_SELECTER_HISTORY",
    MAINACTIVITY_ID = "MAINACTIVITY_ID",
    MAINACTIVITY_SUGGESTERID = "MAINACTIVITY_SUGGESTERID",
    MAINACTIVITY_ISFULLYCOMPLETED = "MAINACTIVITY_ISFULLYCOMPLETED",
    MAINACTIVITY_LABEL = "MAINACTIVITY_LABEL",
    GOAL = "GOAL",

    //SECONDARY ACTIVITY
    WITHSECONDARYACTIVITY = "WITHSECONDARYACTIVITY",
    SECONDARYACTIVITY = "SECONDARYACTIVITY",
    SECONDARYACTIVITY_LABEL = "SECONDARYACTIVITY_LABEL",
    SECONDARYACTIVITY_SUGGESTERID = "SECONDARYACTIVITY_SUGGESTERID",

    //SCORE
    QUALITY_SCORE = "QUALITY_SCORE", //QUALITY SCORE
    QUALITY_SCORE_SUBSTRACT_POINTS = "QUALITY_SCORE_SUBSTRACT_POINTS", //POINT TO SUBSTRACT FOR CALCULATE SCORE

    //ROUTE
    ROUTE = "ROUTE",
    FOOT = "FOOT",
    BICYCLE = "BICYCLE",
    TWOWHEELSMOTORIZED = "TWOWHEELSMOTORIZED",
    PRIVATECAR = "PRIVATECAR",
    OTHERPRIVATE = "OTHERPRIVATE",
    PUBLIC = "PUBLIC",
}

//enums not array
export enum FieldNameEnumWorkTIme {
    FIRSTNAME = "FIRSTNAME",
    SURVEYDATE = "SURVEYDATE",
    WEEKTYPE = "WEEKTYPE",
    ISCLOSED = "ISCLOSED",
    ISENVOYED = "ISENVOYED",
    ISVALIDATED = "ISVALIDATED",
    ISLOCKED = "ISLOCKED",
}
