export enum LocalStorageVariableEnum {
    IS_EDITED_SUMMARY = "IS_EDITED_SUMMARY",
    IS_GLOBAL = "IS_GLOBAL",
    IS_DEMO_MODE = "IS_DEMO_MODE",
    ID_HOUSEHOLD = "ID_HOUSEHOLD",
    IDSURVEY_CURRENT = "IDSURVEY_CURRENT",
}
