/// <reference types="vite-envs/client" />
type ImportMetaEnv = {
  // Auto-generated by `npx vite-envs update-types` and hot-reloaded by the `vite-env` plugin
  // You probably want to add `/src/vite-env.d.ts` to your .prettierignore
  VITE_STROMAE_BACK_OFFICE_API_BASE_URL: string
  VITE_EDT_ORGANISATION_API_BASE_URL: string
  VITE_KEYCLOAK_AUTHORITY: string
  VITE_KEYCLOAK_CLIENT_ID: string
  VITE_KEYCLOAK_REDIRECT_URI: string
  VITE_HOUSE_REFERENCE_REGULAR_EXPRESSION: string
  VITE_SEPARATOR_SUGGESTER: string
  VITE_NODE_ENV: string
  VITE_CHROMIUM_PATH: string
  VITE_NUM_ACTIVITY_SURVEYS: string
  VITE_NUM_WORKTIME_SURVEYS: string
  VITE_REVIEWER_ROLE: string
  VITE_SURVEYED_ROLE: string
  BASE_URL: string
  MODE: string
  DEV: boolean
  PROD: boolean
  // @user-defined-start
  /*
   *  You can use this section to explicitly extend the type definition of `import.meta.env`
   *  This is useful if you're using Vite plugins that define specific `import.meta.env` properties.
   *  If you're not using such plugins, this section should remain as is.
   */
  SSR: boolean;
  // @user-defined-end
}

interface ImportMeta {
  // Auto-generated by `npx vite-envs update-types`

  url: string

  readonly hot?: import('vite-envs/types/hot').ViteHotContext

  readonly env: ImportMetaEnv

  glob: import('vite-envs/types/importGlob').ImportGlobFunction
}
